sonar.projectKey=mauriciovelasquezduoc_ep02_ing_devops_frontend
sonar.organization=mauriciovelasquezduoc
sonar.projectName=ep02-frontend

sonar.sources=src
sonar.tests=src/test
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/reports/**,**/*.test.{js,jsx},src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
